
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 20 23:33:06 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 25;
  public static final int MOD = 19;
  public static final int IDENT = 23;
  public static final int PLUS = 15;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 8;
  public static final int CHAR = 21;
  public static final int SEMI = 5;
  public static final int DECREMENT = 27;
  public static final int LBRACK = 24;
  public static final int RETURN = 9;
  public static final int LPAREN = 6;
  public static final int LBRACE = 3;
  public static final int SUB = 16;
  public static final int COMMA = 10;
  public static final int NUMBER = 20;
  public static final int EOF = 0;
  public static final int DIV = 18;
  public static final int INCREMENT = 26;
  public static final int PROG = 2;
  public static final int CONST = 13;
  public static final int PRINT = 11;
  public static final int error = 1;
  public static final int ASSIGN = 28;
  public static final int NEW = 14;
  public static final int BOOL = 22;
  public static final int MUL = 17;
  public static final int VOID = 12;
}

